### ISSUE TITLE
Collections: Space below cover images

### ISSUE THREAD

**Issue by garrying** [MaximSiebert/Theme2018#21]
<img width="915" alt="screen shot 2018-03-02 at 2 17 51 pm" src="https://user-images.githubusercontent.com/227587/36917398-b352187e-1e24-11e8-92b5-6ed59847e225.png">
- Note that Frame and Gutter are None, and the override color is showing

**Comment by MaximSiebert** [comment]
This will always happen when images are different sizes, I'm aligning to top / bottom / center so there will always be cases like this. The example you screenshotted is because the height is a tad shorter than it's neighbor image, and it's aligned to the top - showing the space at the bottom.

Open to suggestions on how to treat this.
