### ISSUE TITLE
Collections: Position jump on initial load

### ISSUE THREAD

**Issue by garrying** [MaximSiebert/Theme2018#5]
![feb-26-2018 12-01-03](https://user-images.githubusercontent.com/227587/36683928-eac0de7a-1aec-11e8-89c8-b503144bd36a.gif)

- Reproducible if you refresh the page, or initial loading of the page
- Possibly an issue on other page types

**Comment by MaximSiebert** [comment]
The jump is due to me calculating the height of the nav on page load and adjusting the padding on the body. This helps guarantee the content is always pushed lower than the fixed navigation. By setting a default, some issues arise when a user puts in a custom logo or changes the font size.

<img width="1424" alt="screen shot 2018-02-27 at 11 51 51 am" src="https://user-images.githubusercontent.com/4451296/36742038-a4f511d6-1bb4-11e8-9244-dc63241eba7c.png">

The best solution IMO, is setting a default to the height of the preset nav, but also calculating on page load so that if they happen to have a large logo, the body margin will be adjusted accordingly. But of course the jump will still happen.

Open to other suggestions if you guys have fixed this problem in other themes
